[workspace]
authors = ["Giovanni Dejan <giovanni.dejan@binus.ac.id>"]
channels = ["conda-forge"]
name = "marimo-playground"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
start = "marimo edit --headless --port 3000"

[dependencies]
marimo = ">=0.19.11,<0.20"
python = ">=3.13,<3.14"
numpy = ">=2.4.2,<3"
nbformat = ">=5.10.4,<6"
ruff = ">=0.15.1,<0.16"
jaxtyping = ">=0.3.7,<0.4"
